name: dest
on:
  workflow_dispatch:
   inputs:
    region:
     description: "Enter your region name : "
     type : string
    
env:
  bucket: teststorage1983
  tf_statefile: terraform.tfstate
  aws-region: ${{ github.event.inputs.region }}

jobs:
  job1:
    
    runs-on: ubuntu-latest

    
    steps:
     
        uses: actions/checkout@v3
      - name: Setup terraform hashicorp
        uses: hashicorp/setup-terraform@v2 
        with:
          terraform_version: 1.1.7
      
      - name: AWS credentials Configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          Aws-region: ${{env.aws-region}}

      
      - name: terraform init  
        run: |
          cd module
          terraform init -reconfigure
      
      - name: terraform destroy
        run: |
          cd module
          terraform destroy -auto-approve 
          
  job2:
    
    runs-on: ubuntu-latest

    
    steps:
     
        uses: actions/checkout@v3
      - name: Setup terraform hashicorp
        uses: hashicorp/setup-terraform@v2 
        with:
          terraform_version: 1.1.7
      
      - name: AWS credentials Configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN}}
          Aws-region: ${{env.aws-region}}

      
      - name: terraform init  
        run: |
          
          terraform init -reconfigure -backend-config="bucket=${{env.bucket}}" -backend-config="key=${{env.tf_statefile}}"
      
      - name: terraform destroy
        run: |
          
          terraform destroy -auto-approve -var-file="terraform.tfstate"
